-- ============================================================
-- Business Management – MCQ Questions (Seed)
-- Unit 3: Finance & Accounts + Unit 5: Operations Management
-- ============================================================

INSERT OR IGNORE INTO mcq_questions (id, category, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES

  ('mcq1', 'Costs & Revenue', 'SL',
   'A product sells for $80. Variable cost per unit is $30. What is the contribution per unit?',
   '$30',
   '$80',
   '$50',
   '$110',
   2,
   'Contribution per unit = Selling Price − Variable Cost = $80 − $30 = $50.',
   1),

  ('mcq2', 'Cash Flow', 'SL',
   'A business has an opening balance of $4,000, cash inflows of $9,000 and cash outflows of $11,500. What is the closing balance?',
   '$1,500',
   '$2,500',
   '−$1,500',
   '$4,500',
   0,
   'Net cash flow = $9,000 − $11,500 = −$2,500. Closing balance = $4,000 − $2,500 = $1,500.',
   2),

  ('mcq3', 'Final Accounts', 'SL',
   'Which of the following is a CURRENT liability?',
   'Machinery',
   'Mortgage (10-year)',
   'Bank overdraft',
   'Goodwill',
   2,
   'A bank overdraft is repayable within 12 months — it is a current liability. Machinery and goodwill are assets; a mortgage is a non-current liability.',
   3),

  ('mcq4', 'Final Accounts', 'HL',
   'A machine costs $60,000, has a residual value of $6,000, and a useful life of 9 years. What is the annual straight-line depreciation?',
   '$6,000',
   '$7,333',
   '$6,667',
   '$60,000',
   0,
   '= (Cost − Residual value) / Useful life = ($60,000 − $6,000) / 9 = $54,000 / 9 = $6,000 per year.',
   4),

  ('mcq5', 'Ratio Analysis', 'SL',
   'A business has sales revenue of $400,000 and gross profit of $100,000. What is the gross profit margin?',
   '25%',
   '40%',
   '75%',
   '100%',
   0,
   'GPM = (Gross profit / Sales revenue) × 100 = ($100,000 / $400,000) × 100 = 25%.',
   5),

  ('mcq6', 'Ratio Analysis', 'SL',
   'Current assets = $60,000. Stock = $25,000. Current liabilities = $30,000. What is the acid test ratio?',
   '2.0',
   '1.17',
   '0.83',
   '1.5',
   1,
   'Acid test = (Current assets − Stock) / Current liabilities = ($60,000 − $25,000) / $30,000 = $35,000 / $30,000 = 1.17. Above the ideal 1:1 benchmark.',
   6),

  ('mcq7', 'Ratio Analysis (HL)', 'HL',
   'Non-current liabilities = $300,000. Capital employed = $750,000. What is the gearing ratio?',
   '25%',
   '40%',
   '60%',
   '75%',
   1,
   'Gearing = (Non-current liabilities / Capital employed) × 100 = ($300,000 / $750,000) × 100 = 40%. Moderate gearing — below the 50% high-gearing threshold.',
   7),

  ('mcq8', 'Investment Appraisal', 'SL',
   'Which statement about NPV is CORRECT?',
   'A negative NPV means the project is profitable',
   'NPV ignores the time value of money',
   'A positive NPV means the investment adds value in today''s money',
   'NPV is simpler to calculate than payback period',
   2,
   'A positive NPV means the present value of future returns exceeds the initial cost — the project adds value in real money terms. NPV explicitly accounts for the time value of money.',
   8),

  ('mcq9', 'Budgets & Variance', 'HL',
   'Budgeted revenue was $60,000. Actual revenue was $54,000. What type of variance is this?',
   'Favourable variance of $6,000',
   'Adverse variance of $6,000',
   'Favourable variance of $54,000',
   'No variance',
   1,
   'Variance = Actual − Budgeted = $54,000 − $60,000 = −$6,000. For revenue, actual < budgeted = ADVERSE variance.',
   9),

  ('mcq10', 'Budgets & Variance', 'HL',
   'Budgeted costs = $40,000. Actual costs = $36,000. What type of variance is this?',
   'Adverse variance of $4,000',
   'Favourable variance of $4,000',
   'Adverse variance of $36,000',
   'No variance',
   1,
   'For costs: actual < budgeted = FAVOURABLE. The business spent $4,000 less than planned, which is positive.',
   10),

  ('mcq11', 'Breakeven', 'SL',
   'Fixed costs = $15,000. Selling price = $50. Variable cost = $20. What is the breakeven output?',
   '300 units',
   '500 units',
   '750 units',
   '400 units',
   1,
   'Contribution = $50 − $20 = $30. BEQ = Fixed costs / Contribution = $15,000 / $30 = 500 units.',
   11),

  ('mcq12', 'BMT Tools', 'SL/HL',
   'A business sells existing products in a brand new overseas market. Which Ansoff strategy is this?',
   'Market Penetration',
   'Product Development',
   'Market Development',
   'Diversification',
   2,
   'Market Development = existing product into a new market. This is medium-risk as the product is proven but the market is unfamiliar.',
   12),

  ('mcq13', 'Sources of Finance', 'SL',
   'Which is an INTERNAL source of finance?',
   'Bank loan',
   'Retained profit',
   'Venture capital',
   'Crowdfunding',
   1,
   'Retained profit is generated from within the business — it is an internal source of finance. All others require a third party.',
   13),

  ('mcq14', 'Costs & Revenue', 'SL',
   'Factory rent is $5,000 per month regardless of output. What type of cost is this?',
   'Variable cost',
   'Direct cost',
   'Fixed cost',
   'Semi-variable cost',
   2,
   'Factory rent does not change with the level of output — it is a fixed cost.',
   14),

  ('mcq15', 'Ratio Analysis (HL)', 'HL',
   'A business has debtor days of 65 and the industry average is 30. What does this suggest?',
   'The business collects payments faster than rivals',
   'The business has too much stock',
   'The business is very slow at collecting debts — a cash flow risk',
   'The business has high gearing',
   2,
   'High debtor days (65 vs industry 30) means customers are taking far longer than average to pay. This ties up cash and increases cash flow risk. The business should tighten credit control.',
   15),

  ('mcq16', 'Sources of Finance', 'SL',
   'Big Deal installed solar panels on a store roof. What type of expenditure is this?',
   'Revenue expenditure',
   'Capital expenditure',
   'Indirect cost',
   'Trade credit',
   1,
   'Solar panels are a fixed asset lasting more than one year — this is capital expenditure. Revenue expenditure covers day-to-day running costs.',
   16),

  ('mcq17', 'Costs & Revenue', 'SL',
   'Dunn Auto Repair pays Keith a fixed salary of $5,000/month to handle accounting. This is best classified as:',
   'A variable cost',
   'A direct cost',
   'A fixed indirect cost',
   'A revenue stream',
   2,
   'Keith''s salary is fixed (doesn''t change with output) and indirect (not directly tied to any single repair job) — making it a fixed indirect cost/overhead.',
   17),

  ('mcq18', 'Final Accounts', 'SL',
   'Crispy Collin''s has trade creditors of $35,000 and a bank overdraft of $2,500. What are its total current liabilities?',
   '$35,000',
   '$32,500',
   '$37,500',
   '$2,500',
   2,
   'Current liabilities = Bank overdraft + Trade creditors + Other short-term loans = $2,500 + $35,000 + $0 = $37,500.',
   18),

  ('mcq19', 'Ratio Analysis', 'SL',
   'Cedar Hill Books had a current ratio of 1.75:1 in Year 1, falling to 1.55:1 in Year 3. What does this trend suggest?',
   'Cedar Hill is becoming more profitable',
   'Cedar Hill''s liquidity is declining',
   'Cedar Hill is taking on more long-term debt',
   'Cedar Hill''s gross profit margin is rising',
   1,
   'A falling current ratio indicates declining short-term liquidity — the business has less current assets relative to current liabilities each year.',
   19),

  ('mcq20', 'Investment Appraisal', 'SL',
   'On Air Sports paid $6m upfront for broadcast rights generating $2m/year for 8 years. What is the payback period?',
   '2 years',
   '3 years',
   '4 years',
   '6 years',
   1,
   '$2m + $2m + $2m = $6m after 3 years. Payback period = 3 years exactly.',
   20),

  ('mcq21', 'Budgets & Variance', 'HL',
   'Müller Foods budgeted advertising costs of $1,000m but actual costs were $1,039m. What is this variance?',
   '$39m favourable',
   '$39m adverse',
   '$961m favourable',
   '$1,039m adverse',
   1,
   'For costs: actual ($1,039m) > budgeted ($1,000m) = ADVERSE. Müller spent more on advertising than planned, hurting profit.',
   21),

  ('mcq22', 'Ratio Analysis (HL)', 'HL',
   'Fresh Cucina has non-current liabilities of $218m and total equity of $427m. What is its gearing ratio (approximately)?',
   '51%',
   '34%',
   '66%',
   '22%',
   1,
   'Capital employed = Non-current liabilities + Equity = $218m + $427m = $645m. Gearing = $218m / $645m × 100 = 33.8% ≈ 34%.',
   22),

  ('mcq23', 'Cash Flow', 'SL',
   'Which strategy provides the FASTEST solution to a cash flow crisis?',
   'Launching a new product',
   'Debt factoring',
   'Applying for a long-term loan',
   'Reducing prices by 5%',
   1,
   'Debt factoring — selling outstanding invoices to a third party immediately — provides the fastest cash injection. New products, long-term loans, and price cuts all take time to generate cash.',
   23),

  ('mcq24', 'Final Accounts', 'HL',
   'Using the units of production method, a machine costs $23,500, has a residual value of $1,000 and estimated life of 45,000 hours. What is depreciation per hour?',
   '$0.25',
   '$0.50',
   '$0.75',
   '$1.00',
   1,
   '= (Cost − Residual value) / Estimated total units = ($23,500 − $1,000) / 45,000 = $22,500 / 45,000 = $0.50 per hour.',
   24),

  ('mcq25', 'Sources of Finance', 'SL',
   'Manuel at Hail Cheeser! is considering selling shares to friends and family. What must he do first?',
   'Register as a sole trader',
   'Become a private limited company',
   'Apply for crowdfunding',
   'Obtain microfinance',
   1,
   'To sell shares to friends and family, Manuel must incorporate as a private limited company (Ltd). Sole traders and partnerships cannot issue shares.',
   25);
