-- ════════════════════════════════════════════════════════════════════════════
-- 0045 · UKHC History Notes — Castro's Cuba (P2-AUTH) & WWI Detail (P2-WAR)
--        Flashcards, MCQs, written questions, checklist items
-- ════════════════════════════════════════════════════════════════════════════


-- ══════════════════════════════════════════════════════════════════════════
-- A. CASTRO'S CUBA  (unit = 'P2-AUTH', category = '6. Cuba (Castro)')
-- ══════════════════════════════════════════════════════════════════════════

-- ── A1. New Checklist Items ───────────────────────────────────────────────
-- Existing section hist-p2-auth-cl-6 has 7 items. Add more detailed ones.
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-auth-cl-6', 'I can explain the conditions under Batista that led to Castro''s emergence', 8);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-auth-cl-6', 'I can describe the Moncada Barracks attack (1953) and its significance', 9);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-auth-cl-6', 'I can analyse Castro''s guerrilla campaign in the Sierra Maestra (1956-59)', 10);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-auth-cl-6', 'I can explain the role of propaganda in Castro''s rise (Radio Rebelde, NYT interview)', 11);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-auth-cl-6', 'I can discuss Castro''s consolidation of power 1959-65 (use of force, legal methods, charisma)', 12);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-auth-cl-6', 'I can analyse the Bay of Pigs invasion and its impact on Castro''s position', 13);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-auth-cl-6', 'I can explain the nature and treatment of opposition (Escambray, Matos, Morgan)', 14);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-auth-cl-6', 'I can evaluate the Special Period (1991-96) and its threat to Castro''s regime', 15);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-auth-cl-6', 'I can discuss Castro''s education policies with specific statistics', 16);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-auth-cl-6', 'I can evaluate Castro''s healthcare policies and their limitations', 17);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-auth-cl-6', 'I can analyse the impact of Castro''s policies on women (FCW, Family Code, literacy campaign)', 18);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-auth-cl-6', 'I can discuss the extent of authoritarian control achieved by Castro', 19);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-auth-cl-6', 'I can compare Castro''s Moncada Programme aims with Hitler''s 25 Points', 20);

-- ── A2. New Flashcards ───────────────────────────────────────────────────
-- Existing topic hist-p2-auth-fc-6 has 5 cards (sort_order 1-5). Continue from 6.

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Batista''s Regime', 'Fulgencio Batista ruled Cuba as a US-backed dictator. His regime was corrupt, authoritarian, and served US economic interests. Widespread poverty, inequality, and political repression created conditions for revolution.', 6);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Moncada Barracks Attack (26 July 1953)', 'Castro''s failed attack on the Moncada military barracks in Santiago. Most attackers died or were captured. Castro was tried and gave his famous "History Will Absolve Me" speech, gaining national prominence. Released in 1955 after international pressure.', 7);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', '"History Will Absolve Me" Speech', 'Castro''s defence speech at his Moncada trial. He highlighted the illegal nature of Batista''s coup, outlined his programme (end corruption, land reform, literacy, healthcare, reduced US influence), and gained a national platform. International pressure led to his release in 1955.', 8);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Granma Expedition (1956)', 'Castro and 82 revolutionaries sailed from Mexico on the yacht Granma to Cuba. They were met by Batista''s military and most died, with a few survivors (including Castro, Guevara) fleeing to the Sierra Maestra mountains to begin guerrilla warfare.', 9);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Guerrilla Tactics in Sierra Maestra', 'Castro''s forces used classic guerrilla tactics: retreat when attacked, hit-and-run attacks, small autonomous groups, mobile forces, reliance on peasant support. They wore down Batista''s conventional army, which failed to use counterinsurgency tactics and instead relied on artillery and tanks (static targets).', 10);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Sierra Maestra Campaign (1956-59)', '1956-57: Survival phase, developing peasant support, La Plata Garrison attack, El Uvero victory. Batista withdrew forces, ceding Sierra Maestra. Guerrillas established base at La Plata, ran Radio Rebelde (Cuba''s most popular station) and El Cubano Libre newspaper. Castro ate same portions as his troops, establishing charismatic leadership.', 11);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Battle of Santa Clara (Dec 1958)', 'Che Guevara captured Santa Clara with a 300:4000 troop ratio, highlighting Fidelista military competence. This was the decisive battle; Batista fled on 31 December 1958, and Castro arrived in Havana on 8 January 1959 after travelling through Cuba. The rebel army never exceeded ~2000 men.', 12);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Castro''s Propaganda Methods', 'Moncada trial gave national prominence. "History Will Absolve Me" speech. Granma expedition promise kept ("I will return by 1957"). El Cubano Libre newspaper. Radio Rebelde — most popular station in Cuba. Herbert Matthews NYT interview and ABC TV interview established international sympathy. Emphasised ending corruption.', 13);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Consolidation of Power (1959-65)', 'The period 1959-65 saw Castro eliminate all external and internal opposition. Methods included: use of force (trials/executions of Batista supporters), legal methods (nationalisation, land reform), charismatic leadership, and propaganda dissemination. By 1965 there was no active opposition.', 14);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Bay of Pigs Invasion (April 1961)', 'CIA-backed attempt by Cuban exiles to overthrow Castro. Failed miserably. Castro used it to highlight US interference and consolidate domestic support. Both Castro and the USSR concluded the US lacked intention to take significant direct action against Cuba.', 15);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Escambray Rebellion', 'Anti-Communist rebels (wealthier peasants, middle class, farmers opposing expropriation, Batista loyalists) used guerrilla warfare in Escambray Mountains. CIA pulled out after Bay of Pigs failure. No outstanding leaders, outnumbered, no popular support. Castro used overwhelming resources to eradicate them — "comb the brush, elbow to elbow".', 16);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Opposition Figures: Matos & Morgan', 'Hubert Matos: concerned about Communism entering revolutionary government, had supported Castro. William Alexander Morgan: supported Castro''s revolution until it turned Communist — he opposed Communism. Both were notable political figures/elites who were suppressed.', 17);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Castro''s Foreign Policy', 'CIA ran several failed assassination attempts. Doctor Diplomacy: sending doctors to less-developed countries (particularly in Africa) improved relations and helped avoid consequences of the US embargo. Cold War alignment with Soviets (85% of trade). Cuba supported liberation movements internationally.', 18);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'The Special Period (1991-96)', 'Collapse of USSR (1991) devastated Cuba — Soviets were 85% of trading partners, economy fell 40%. Severe hardship: bikes replaced cars (no fuel), power shortages. US passed Torricelli Act (1992) and Helms-Burton Act (1996) restricting trade. Castro''s power was most at risk during this period.', 19);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Special Period Response', 'Cuba emphasised revolutionary ideology and sought new markets. Pragmatic policies: dollarisation of economy, encouraging private enterprise, inviting foreign firms (1995). By mid-1990s 50+ dissident groups emerged (first time since 1965). 100 members of Concilio Cubano arrested in 1996. By 1996 situation broadly improved. US flights to Cuba began in 1998.', 20);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Moncada Programme Aims', 'Castro''s programme from "History Will Absolve Me": (1) End corruption, (2) Improved working conditions and profit-sharing, (3) Land and agrarian reform, (4) Reduced US influence and Cuban nationalism, (5) Increased literacy and improved healthcare, plus infrastructure/sewers.', 21);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Castro''s Education Policies', 'Largely successful. Teachers increased from 20,000 to 60,000 (pre-Revolution to 1963). 1961 literacy campaign raised literacy from 40% to 96% — highest in Latin America. Primary enrollment: 800,000 (1958-59) to 3.3M (1982-83). Secondary schools: 80 to 1,900. BUT: brain drain (teachers left 1959-61), high investment reduced funds for other areas, and education used for ideological indoctrination.', 22);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Castro''s Healthcare Policies', 'Made healthcare free for all. 1,100 doctors graduated annually. Eliminated polio through immunisation; Cuba declared malaria-free. Improved infant mortality and life expectancy. BUT: shortages through 1980s, US embargo restricted medicine access, initially undertrained staff, and gains did not survive the Special Period.', 23);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Population & Demographics Under Castro', 'Population grew from 5.8M (1953) to 8.5M (1970). Birth rates surged from 27/1000 (1958) to 37/1000 (1962). Marriage rates doubled 1958-61. BUT: increased birth/marriage rates did not translate to long term. Despite healthcare reform, emigration remained high and Cuba''s population is now shrinking.', 24);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Impact on Women in Cuba', 'Federation of Cuban Women (1960): expanded to 2.6M members. Women''s employment rose from 13% (1958) to 44% (2008). Women held 43% of parliament (2008). 1961 Literacy Campaign mobilised 100,000 women; 56% of newly literate were women. 1975 Family Code mandated egalitarian family law. BUT: largely ignored — women did 75% of domestic labour in 1990s. Cultural resistance (machismo). Special Period pushed women into sex work.', 25);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', '1975 Family Code', 'Aimed to dismantle patriarchal family structures. Required men to do half the chores. Provided maternity cover, abortions, day-care. Simplified divorce procedures. BUT largely ignored — 76% of women who entered the labour force in 1969 dropped out within a year. Tanay: "good intentions, but fundamentally useless".', 26);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Impact on Minorities', 'LGBTQ+ individuals were incarcerated for a period. Castro''s regime repressed homosexuality as "counter-revolutionary". This represents a significant failure in the regime''s social policies and contradicts claims of egalitarianism.', 27);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Pact of Caracas (1958)', 'All opposition groups agreed to end the Batista regime and restore democracy. Castro did not follow through on the democratic restoration promise after taking power, instead consolidating a one-party state.', 28);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Battle of La Plata (1958)', 'Part of Batista''s Verano Offensive — his last major attempt after US support ended. 2 battalions vs a smaller rebel force. Result: 3 rebel injuries vs ~250 Batista casualties. Demonstrated the competence of guerrilla forces against conventional military.', 29);
INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-auth-fc-6', 'Castro''s Ideological Flexibility', '"Anything anti-communist is now also anti-revolutionary." Castro did not read Das Kapital before calling himself a Marxist-Leninist. Economic ideology was a matter of political convenience rather than heartfelt beliefs. Concerns that elections could be influenced by the United States justified one-party rule.', 30);

-- ── A3. New MCQ Questions ────────────────────────────────────────────────

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-300', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'The Moncada Barracks attack took place in:', '1950', '1953', '1956', '1959', 1, 'The Moncada Barracks attack occurred on 26 July 1953. Though it failed militarily, it gave Castro national prominence through his trial and "History Will Absolve Me" speech.', 300);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-301', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'Castro''s guerrilla forces in the Sierra Maestra never exceeded approximately:', '200 men', '2,000 men', '10,000 men', '50,000 men', 1, 'The rebel army never exceeded approximately 2,000 men (estimates range from 300 to 8,000 but 2,000 is the best estimate, according to Wolf). Despite this small size, they defeated Batista''s much larger conventional forces.', 301);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-302', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'Which battle saw Che Guevara defeat forces at a 300:4000 ratio?', 'Battle of La Plata', 'Battle of Santa Clara', 'Battle of El Uvero', 'Battle of Havana', 1, 'On 31 December 1958, Che Guevara captured Santa Clara with a roughly 300:4000 troop ratio, demonstrating the competence of the Fidelistas. Batista fled Cuba the same day.', 302);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-303', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'The Bay of Pigs invasion occurred in:', 'January 1959', 'April 1961', 'October 1962', 'March 1960', 1, 'The CIA-backed Bay of Pigs invasion took place in April 1961 and failed miserably. Castro used it to highlight US interference and consolidate domestic support.', 303);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-304', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'What percentage of Cuba''s trade was with the Soviet Union before 1991?', '50%', '65%', '85%', '95%', 2, 'The Soviet bloc accounted for 85% of Cuba''s trading partners. The collapse of the USSR in 1991 led to a 40% decline in Cuba''s economy, triggering the Special Period.', 304);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-305', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'The Torricelli Act restricting trade with Cuba was passed in:', '1989', '1992', '1996', '2000', 1, 'The Torricelli Act was passed in 1992, followed by the Helms-Burton Act in 1996. Both aimed to tighten the US trade embargo against Cuba during the Special Period.', 305);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-306', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'Cuba''s 1961 literacy campaign raised literacy rates to approximately:', '70%', '85%', '96%', '100%', 2, 'The 1961 literacy campaign raised literacy from 40% to a reported 96%, the highest in Latin America and one of the highest in the world at the time.', 306);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-307', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'The number of teachers in Cuba increased from 20,000 pre-Revolution to how many by 1963?', '30,000', '45,000', '60,000', '100,000', 2, 'The number of teachers tripled from 20,000 to 60,000 between the pre-Revolution period and 1963, though this was partially offset by the brain drain of teachers leaving Cuba (1959-1961).', 307);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-308', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'The Federation of Cuban Women was established in:', '1953', '1959', '1960', '1965', 2, 'The Federation of Cuban Women (FMC) was established in 1960 to integrate women into the workforce and promote female literacy and gender equality. It expanded to 2.6 million members.', 308);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-309', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'Women''s employment in Cuba rose from 13% in 1958 to what percentage by 2008?', '25%', '33%', '44%', '55%', 2, 'Women''s employment rose from 13% (1958) to 44% (2008). Women also held 43% of parliamentary seats by 2008, though cultural resistance (machismo) limited the real impact of gender policies.', 309);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-310', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'The 1975 Family Code in Cuba aimed to:', 'Restrict women''s access to education', 'Dismantle patriarchal family structures and mandate shared domestic labour', 'Encourage higher birth rates', 'Nationalise childcare entirely', 1, 'The 1975 Family Code aimed to create egalitarian family law, requiring men to do half the chores, providing maternity cover, abortions, and day-care, and simplifying divorce. However, it was largely ignored in practice.', 310);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-311', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'Which of the following was NOT a guerrilla tactic used by Castro in the Sierra Maestra?', 'Hit-and-run attacks', 'Small autonomous groups', 'Large-scale frontal assaults on cities', 'Retreating when attacked', 2, 'Castro''s guerrillas used classic guerrilla tactics: retreat when attacked, hit-and-run attacks, small autonomous groups, and mobile forces with peasant support. They avoided large-scale frontal assaults, which was Batista''s failing strategy.', 311);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-312', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'Radio Rebelde was significant because it:', 'Was used by Batista to spread propaganda', 'Became the most popular radio station in Cuba, spreading Castro''s message', 'Was funded by the CIA', 'Broadcast exclusively in English for international audiences', 1, 'Radio Rebelde became the most popular radio station in Cuba, spreading revolutionary propaganda and Castro''s message from the Sierra Maestra. Along with the newspaper El Cubano Libre, it was key to building support.', 312);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-313', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'The Escambray Rebellion was primarily composed of:', 'Communist guerrillas', 'Wealthier peasants, middle class, and Batista loyalists opposing Castro', 'Foreign mercenaries', 'University students', 1, 'The Escambray rebels were mainly wealthier peasants, middle class, and local farmers who opposed expropriation and reorganisation, plus Batista loyalists. They had no outstanding leaders, were outnumbered, and lacked popular support.', 313);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-314', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'Castro''s period of consolidation is generally considered to be:', '1953-1956', '1956-1959', '1959-1965', '1965-1975', 2, 'The consolidation period was 1959-1965 — from Castro taking power to when all active external and internal opposition had been eliminated. His key acts were 1959-1961, and foreign opposition died down by 1965.', 314);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-315', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'Which historian described Cuba''s education policies as achieving egalitarian goals more than anywhere else?', 'Fischer', 'Perez', 'Tanay', 'Wolf', 1, 'Perez stated: "Nowhere was the quest for an egalitarian society more fully attained than in the area of education." This reflects the widely acknowledged success of Castro''s education reforms.', 315);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-316', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'What was a key pragmatic economic response during Cuba''s Special Period?', 'Increased trade with the USSR', 'Dollarisation of the economy and inviting foreign firms', 'Nationalisation of all remaining private businesses', 'Military expansion', 1, 'During the Special Period, Cuba pursued pragmatic policies including dollarisation, encouraging private enterprise, and inviting foreign firms (1995). However, under George W. Bush''s pressure, Cuba moved against dollarisation by 2004.', 316);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-317', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'Cuba''s population grew from 5.8 million in 1953 to approximately how many by 1970?', '6.5 million', '7.5 million', '8.5 million', '10 million', 2, 'Cuba''s population increased from 5.8 million (1953) to 8.5 million (1970). Birth rates surged from 27/1000 (1958) to 37/1000 (1962), though this increase did not sustain long-term.', 317);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-318', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'What was the Pact of Caracas (1958)?', 'A military alliance between Cuba and Venezuela', 'An agreement by all opposition groups to end Batista''s regime and restore democracy', 'A trade deal between Cuba and the Soviet Union', 'A peace treaty ending the Cuban Revolution', 1, 'The Pact of Caracas (1958) saw all opposition groups agree to end the Batista regime and restore democracy. Castro, however, did not follow through on the democratic restoration promise after taking power.', 318);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-319', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'By the mid-1990s, how many dissident groups had emerged in Cuba?', 'Fewer than 10', 'Over 50', 'Over 200', 'Over 500', 1, 'By the mid-1990s, over 50 dissident groups had emerged — the first time since 1965 with such significant dissidence. However, Castro''s regime quelled this opposition with force, arresting 100 members of Concilio Cubano in 1996.', 319);

-- ── A4. New Written Questions ────────────────────────────────────────────

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-130', '6. Cuba (Castro)', 'SL/HL', 'short_answer', 'P2-AUTH', 15, 'Evaluate the role of guerrilla warfare in Castro''s rise to power.', '• Band 5 (13-15): Detailed analysis of guerrilla tactics (retreat when attacked, hit-and-run, small autonomous groups, peasant support) and their effectiveness against Batista''s conventional forces. Must discuss specific engagements (La Plata, El Uvero, Santa Clara) with evidence. Should also evaluate the role of propaganda (Radio Rebelde, NYT interview) and political factors alongside military ones. The rebel army never exceeded ~2,000 men yet defeated a much larger force.
• Band 3 (7-9): Some relevant knowledge of guerrilla tactics but limited specific evidence or evaluation of relative importance.
• Band 1 (1-3): Vague description with no specific military engagements or analysis.', 130);

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-131', '6. Cuba (Castro)', 'SL/HL', 'short_answer', 'P2-AUTH', 15, 'To what extent was Castro''s consolidation of power (1959-65) reliant on the use of force?', '• Band 5 (13-15): Balanced evaluation weighing use of force (trials/executions, crushing Escambray Rebellion, suppressing Matos/Morgan) against other methods: legal methods (nationalisation, land reform), charismatic leadership (personal appeal, eating same rations as troops), propaganda (Radio Rebelde, highlighting Bay of Pigs as US interference), and ideological flexibility. Must consider that consolidation was complete by 1965.
• Band 3 (7-9): Some analysis of force and other methods but may lack balance or specific evidence.
• Band 1 (1-3): Simple assertion about force with no supporting evidence.', 131);

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-132', '6. Cuba (Castro)', 'SL/HL', 'short_answer', 'P2-AUTH', 15, 'Evaluate the successes and limitations of Castro''s social policies in education and healthcare.', '• Band 5 (13-15): Detailed evaluation with specific statistics. Education: teachers 20,000→60,000, literacy 40%→96%, primary enrollment 800,000→3.3M, secondary schools 80→1,900. Perez: "nowhere was the quest for an egalitarian society more fully attained than in education." Healthcare: free for all, 1,100 doctors/year, polio eliminated, malaria-free. BUT: brain drain of teachers 1959-61, indoctrination concerns, medicine shortages due to embargo, healthcare gains did not survive Special Period. Must reach a balanced judgement.
• Band 3 (7-9): Some statistics but limited evaluation of successes vs. limitations.
• Band 1 (1-3): General claims about education/healthcare without evidence.', 132);

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-133', '6. Cuba (Castro)', 'SL/HL', 'short_answer', 'P2-AUTH', 15, 'To what extent did the Special Period (1991-96) threaten Castro''s hold on power?', '• Band 5 (13-15): Detailed analysis of the crisis: USSR collapse, 85% of trade lost, economy fell 40%, severe hardship (no fuel, power shortages), Torricelli Act (1992), Helms-Burton Act (1996). Response: pragmatic policies (dollarisation, private enterprise, foreign firms), ideological emphasis, US as bogeyman uniting Cubans. 50+ dissident groups emerged but were suppressed (Concilio Cubano arrests 1996). Must evaluate whether the regime was genuinely threatened or adapted effectively.
• Band 3 (7-9): Some knowledge of the Special Period but limited analysis of the threat to power.
• Band 1 (1-3): Vague awareness of economic difficulties without specific evidence.', 133);

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-134', '6. Cuba (Castro)', 'SL/HL', 'short_answer', 'P2-AUTH', 15, 'Evaluate the impact of Castro''s policies on women in Cuba.', '• Band 5 (13-15): Detailed analysis of policies and their real impact. Achievements: Federation of Cuban Women (1960, 2.6M members), employment 13%→44%, 43% of parliament (2008), literacy campaign mobilised 100,000 women (56% of newly literate were women), women dominate higher education (70% med school 2008). 1975 Family Code mandated equality. 1968 nationalisation: 90% of new administrators were women. BUT: Family Code largely ignored (women did 75% of domestic labour in 1990s), 76% of women who entered labour force in 1969 dropped out within a year, cultural machismo persisted, Special Period pushed women into sex work. Tanay: "good intentions, but fundamentally useless."
• Band 3 (7-9): Some knowledge of policies but limited analysis of gap between policy and reality.
• Band 1 (1-3): Vague claims about gender equality without evidence.', 134);

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-135', '6. Cuba (Castro)', 'SL/HL', 'short_answer', 'P2-AUTH', 15, 'Compare and contrast the emergence of Castro and one other authoritarian leader.', '• Band 5 (13-15): Systematic comparison of conditions (economic, political, social) and methods (use of force, propaganda, legal, charismatic) for Castro and another leader (e.g., Hitler, Mao). Castro: Batista''s corruption, US economic dominance, guerrilla warfare, Moncada/Sierra Maestra, propaganda (Radio Rebelde). Must show genuine comparison with similarities and differences, not two separate narratives.
• Band 3 (7-9): Some comparison but may be largely descriptive or two separate accounts.
• Band 1 (1-3): Vague comparison with no specific evidence from either case.', 135);

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-136', '6. Cuba (Castro)', 'SL/HL', 'short_answer', 'P2-AUTH', 15, 'To what extent did Castro achieve authoritarian control over Cuba?', '• Band 5 (13-15): Evaluative argument assessing the degree of control. Evidence of control: one-party state, elimination of opposition by 1965, censorship, CDR surveillance, control of education as propaganda. Evidence of limitations: Special Period dissidence (50+ groups), brain drain/emigration, economic failures, cultural resistance to social policies (machismo, Family Code ignored), reliance on USSR. Must define what "authoritarian control" means and reach a clear judgement.
• Band 3 (7-9): Some analysis but may overstate or understate degree of control.
• Band 1 (1-3): Simple assertion without evidence or criteria for judgement.', 136);


-- ══════════════════════════════════════════════════════════════════════════
-- B. WWI DETAILED CAUSES, COURSE & CONSEQUENCES  (unit = 'P2-WAR')
-- ══════════════════════════════════════════════════════════════════════════

-- ── B1. New Checklist Section ─────────────────────────────────────────────
INSERT OR IGNORE INTO history_checklist_sections (id, title, color, unit, sort_order) VALUES ('hist-p2-war-cl-7', '7. WWI: Detailed Causes, Course & Consequences', '#C4A36A', 'P2-WAR', 107);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-war-cl-7', 'I can explain the ANIMAL framework for WWI causes (Alliances, Nationalism, Imperialism, Militarism, Assassination, List of events)', 1);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-war-cl-7', 'I can describe the Concert of Europe and why it failed', 2);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-war-cl-7', 'I can analyse Balkan tensions (pan-Slavism, Bosnia-Herzegovina annexation, Serbian nationalism)', 3);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-war-cl-7', 'I can discuss the Moroccan Crises (1905, 1911) and their significance', 4);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-war-cl-7', 'I can explain Weltpolitik and the naval arms race (Dreadnoughts)', 5);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-war-cl-7', 'I can analyse the July Crisis and the role of the ''blank cheque''', 6);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-war-cl-7', 'I can describe key Western Front battles with casualty figures (Verdun, Somme)', 7);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-war-cl-7', 'I can explain the Eastern Front and the Brusilov Offensive', 8);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-war-cl-7', 'I can discuss US entry (submarine warfare, Zimmerman Telegram)', 9);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-war-cl-7', 'I can analyse the Ludendorff Offensive and why it failed', 10);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-war-cl-7', 'I can explain naval warfare (Jutland, U-boats, convoys) and air warfare', 11);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-war-cl-7', 'I can discuss the Russian Revolution''s impact and Treaty of Brest-Litovsk', 12);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-war-cl-7', 'I can evaluate the historiographical debate on WWI responsibility (Fischer, Fay, Winter)', 13);
INSERT INTO history_checklist_items (section_id, text, sort_order) VALUES ('hist-p2-war-cl-7', 'I can analyse the Treaty of Versailles terms and consequences in detail', 14);

-- ── B2. New Flashcard Topic & Cards ──────────────────────────────────────
INSERT OR IGNORE INTO history_flashcard_topics (id, label, color, unit, sort_order) VALUES ('hist-p2-war-fc-7', '7. WWI: Detailed Causes, Course & Consequences', '#C4A36A', 'P2-WAR', 7);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'Congress of Vienna (1814-15)', 'After Napoleon''s defeat, the Congress of Vienna aimed to balance the great powers, creating stability and cracking down on republican/democratic challenges. Talleyrand prevented France from losing significant territory. Led to the Concert of Europe — an informal agreement maintaining European balance of power for most of the 19th century.', 1);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'ANIMAL Framework for WWI Causes', 'A = Alliances (Triple Alliance, Triple Entente), N = Nationalism, I = Imperialism, M = Militarism, A = Assassination of Franz Ferdinand (immediate cause), L = List of events c.1871-1914. Long-term causes did not mean war was inevitable — a crisis was still necessary to push governments into conflict.', 2);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'Balkan Tensions', 'Ottoman fragmentation created smaller states (Serbia, Bulgaria), allowing Russia and Austria-Hungary to compete for influence. Russia promoted pan-Slavism. Austria-Hungary annexed Bosnia-Herzegovina in 1908 — Russia was furious but militarily unable to respond. Serbia pushed for a "Greater Serbia" uniting Balkan Slavs. Key Austro-Hungarian leaders wanted to deal with Serbia before it grew stronger.', 3);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'Moroccan Crises (1905 & 1911)', '1905: France moved to control Morocco; Germany objected, threatening war. Algeciras Conference forced Germany to back down. 1911: France sent troops into Morocco; Germany demanded territory; Britain and France gave Germany portions of French Congo. Germany felt "insulted, defeated and humiliated." The crises strengthened the Anglo-French entente.', 4);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'Weltpolitik', 'Kaiser Wilhelm II''s policy of extending German influence worldwide through a powerful navy and colonies. In 1896 he declared "nothing must henceforth be settled in the world without the intervention of Germany." German Foreign Minister: "we too demand our place in the sun." This threatened British and French interests.', 5);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'Naval Arms Race', 'Germany challenged British naval dominance. Britain responded with Dreadnought-class battleships. 1906: Britain had 1 Dreadnought, Germany 0. By 1914: Britain had 29, Germany 17. Germany felt it was losing the arms race, and the gap kept growing — making them believe if war was inevitable, it was better now than later.', 6);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'Alliance System Detail', 'Triple Alliance: Germany + Austria-Hungary (Dual Alliance, formed due to German fears of Russia) + Italy (joined 1882). Defensive alliance with autonomy. Triple Entente: Russia + France (1894, fear of Germany) + Britain (Entente Cordiale 1904, Anglo-Russian Convention 1907). Geographically, Germany was nearly surrounded. "The idea that the alliance system led to war by chain reaction is only superficially compelling" — in 1914, each power joined on its own terms.', 7);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'Military Plans', 'Schlieffen Plan: Attack France through Belgium, capture Paris in 6 weeks, then turn east against Russia (expected 8-week mobilisation). Russia: emphasised early mobilisation. France: Plan XVII — concentrated attack through Lorraine. Austria-Hungary: multi-front concern (Russia, Serbia, Romania), weak technologically. Britain: small standing army, rapid deployment to France, Royal Navy blockade. All plans assumed a short war.', 8);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'July Crisis & Blank Cheque', 'After the assassination of Archduke Franz Ferdinand (28 June 1914), Austria-Hungary delivered a deliberately harsh ultimatum to Serbia (48 hours). Germany offered a "blank cheque" — unconditional support (6 July). Serbia accepted all demands except those violating its constitution. Germany refused Britain''s proposed conference (26 July). German chancellor only backtracked on 29 July when British and Russian intentions became clear.', 9);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'Schlieffen Plan Failure', 'Germans made rapid progress through Belgium and Luxembourg, but: (1) British forces slowed them at Mons, (2) railway damage left railheads 135km behind front lines, (3) gaps in German lines were exploited by the enemy. Germans were stopped at the Battle of the Marne (6-9 September 1914). Both sides entrenched, leading to the "Race to the Sea" — trench lines from Switzerland to the English Channel.', 10);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'Trench Warfare Technology', 'Defenders had enormous advantage. Machine guns: 500 rounds/minute in fixed positions (later evolved into mobile, single-man guns). Britain massively outproduced Germany: 1914 — Britain 300, Germany 500; 1918 — Britain 120,900, Germany 13,000. Attack methods: preliminary artillery bombardment, creeping barrage, mines, poison gas, tanks (from 1916, mainly British/French, 5,000+ by 1918).', 11);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'Battle of Verdun (Feb-Dec 1916)', 'German attack on French fortresses aiming to divert forces through continuous bombardment. A massive battle of attrition: 542,000 French casualties, 430,000 German dead. After 10 months, France held Verdun and Germans gained only 8 km of territory.', 12);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'Battle of the Somme (Jul-Nov 1916)', 'British aimed to break the stalemate and draw Germans from Verdun. Preliminary bombardment and early tank use failed to weaken German trenches. 54,740 casualties (half dead) on the first day. Continued July-November despite losses: 420,000 British, 200,000 French, 500,000 German. Negligible territorial gains.', 13);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'Brusilov Offensive (June-Sep 1916)', 'Russian offensive targeting Austro-Hungarians in Ukraine, partly to relieve Italians. Started well — 96 km gained in June. Stalled due to insufficient supplies; Germans moved troops from Verdun; ended September 1916. Cost 1 million Russian men and created discontent in Russia. But it totally crippled Austro-Hungarian military, which needed significant German support afterwards.', 14);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'US Entry into WWI (April 1917)', 'USA joined Allies due to: (1) German submarine warfare targeting US vessels, (2) Zimmerman Telegram encouraging Mexico to invade the US (massive fail — instead of keeping US focused on Mexico, it brought US into WWI). By March 1918, 250,000 US troops were arriving monthly in Europe, which devastated German morale.', 15);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'Treaty of Brest-Litovsk (1918)', 'Bolsheviks ended Russia''s war with Central Powers. Russia lost: 2.6 million km2 of territory (Poland, Lithuania, Ukraine, Baltics), 75% of iron ore, 90% of coal, 50% of industry, 55 million people, and half its agricultural land. Most spoils went to Germany, freeing them to focus on the Western Front.', 16);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'Ludendorff Offensive (March-June 1918)', 'Germany''s massive final offensive using: hurricane barrages (short, intensive bombardments), and infiltration tactics — smaller stormtrooper detachments attacking weak points for surprise and speed. Initially gained 65 km in the first week. Stalled due to lack of reserves and supplies. Allied tanks and aircraft forced retreat at Second Battle of the Marne (July-August 1918). Retreat became irreversible.', 17);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'War at Sea', 'British naval blockade confined German navy to ports, devastating supplies. Battle of Jutland (1916): British lost 14 ships, Germany 11 — inconclusive but blockade continued. Germany turned to U-boat submarine warfare: 748,000 tons sunk in 1915, 500,000 tons in April 1917 alone. Sinking of Lusitania angered US. British used convoys, Q-ships (disguised military vessels), and depth charges against submarines.', 18);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'War in the Air', 'Initially used for reconnaissance (Battle of Tannenberg, August 1914). Fighter aircraft developed with machine guns — Germans had superior technology but Allies had far more aircraft. Zeppelins used for bombing (easy targets). Strategic bombing possible but not decisive. Aircraft began supporting ground troops (Cambrai, Ludendorff Offensive).', 19);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'Spanish Influenza & Disease', 'Soldiers in trenches faced malaria, typhoid from terrible sanitation. Spanish influenza (January 1918 - December 1920) killed ~120 million people (6% of world population). 500,000 German troops were too ill to fight, significantly impacting the Ludendorff Offensive and the war''s final phase.', 20);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'Collapse of Central Powers (1918)', 'Bulgaria surrendered 29 September, Ottomans 30 October, Austria-Hungary 3 November 1918. They could not sustain conflict: lacked reserves, home situations deteriorated, governments lost appetite for war. A mutiny in the German navy preceded the Armistice (11 November 1918).', 21);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'WWI Responsibility Debate', 'Sidney Bradshaw Fay (US): proposed collective responsibility, opposing sole German blame from Treaty of Versailles. Fritz Fischer: argued Germany deliberately planned war for annexation and colonial expansion. Gerhard Ritter: disagreed with Fischer, noting annexation plans were made when war was underway. JM Winter: "If Germany may be said to have brought about WWI, it did so as part of a political community which collectively let the peace of Europe slip through its fingers." Consensus: collective responsibility with emphasis on German actions.', 22);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'Middle Eastern Theatre', 'Allies aimed to knock Ottomans out of war, boost morale, open Russian supply routes. Gallipoli (ANZAC troops): amphibious assault, highly unsuccessful, 45,000+ dead. Mesopotamia: British captured Basra (1914) for oil, then Baghdad (1917). British encouraged Arab Revolt against Ottomans, promising independence (not honoured). October 1918: Ottoman surrender.', 23);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'Poison Gas in WWI', 'Germans used poison gas at Second Battle of Ypres, gaining 7 km. Allies had 69,000 casualties, Germans 38,000. But gas caused less than 1% of war fatalities — its significance was more psychological. Both sides eventually deployed gas, but effective countermeasures (gas masks) limited its tactical impact.', 24);

INSERT INTO history_flashcards (topic_id, term, definition, sort_order) VALUES ('hist-p2-war-fc-7', 'Eastern Front Overview', 'Russia had faster mobilisation than expected. Russia drove deep into Galicia (Austria-Hungary) but less success against Germany. At Battle of Tannenberg (29 August 1914), Germans encircled and defeated Russians — their closest approach to threatening Germany. After that, fighting remained at the Eastern Front without deep penetration.', 25);

-- ── B3. New MCQ Questions ────────────────────────────────────────────────

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-320', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'The Concert of Europe originated from:', 'The Treaty of Versailles (1919)', 'The Congress of Vienna (1814-15)', 'The Berlin Conference (1884-85)', 'The Hague Conventions (1899)', 1, 'The Concert of Europe was an informal system of maintaining European balance of power that emerged from the Congress of Vienna (1814-15), held after Napoleon''s defeat.', 320);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-321', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'Austria-Hungary annexed Bosnia-Herzegovina in:', '1878', '1903', '1908', '1914', 2, 'Austria-Hungary annexed Bosnia-Herzegovina in 1908. Russia was unable to respond militarily but was furious, and determined to prevent further Austrian expansion in the Balkans.', 321);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-322', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'Weltpolitik was the foreign policy of:', 'Tsar Nicholas II', 'Kaiser Wilhelm II', 'King Edward VII', 'Emperor Franz Joseph', 1, 'Weltpolitik was Kaiser Wilhelm II''s policy of extending German influence worldwide through a powerful navy and colonial expansion. He declared "nothing must henceforth be settled in the world without the intervention of Germany."', 322);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-323', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'By 1914, how many Dreadnought-class battleships did Britain have compared to Germany?', 'Britain 17, Germany 29', 'Britain 29, Germany 17', 'Britain 20, Germany 20', 'Britain 10, Germany 25', 1, 'By 1914 Britain had 29 Dreadnoughts to Germany''s 17. In 1906, Britain had 1 and Germany had none. The naval arms race was a key source of Anglo-German tension.', 323);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-324', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'Germany''s "blank cheque" to Austria-Hungary was issued on:', '28 June 1914', '6 July 1914', '26 July 1914', '1 August 1914', 1, 'On 6 July 1914, Germany offered Austria-Hungary unconditional support (the "blank cheque") against Serbia. This emboldened Austria-Hungary to issue its deliberately harsh ultimatum.', 324);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-325', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'The Germans were stopped at which battle in September 1914, ending the Schlieffen Plan?', 'Battle of Tannenberg', 'Battle of the Marne', 'Battle of Verdun', 'Battle of Ypres', 1, 'The Germans were stopped at the Battle of the Marne (6-9 September 1914). Both sides then entrenched, leading to the "Race to the Sea" and the trench warfare stalemate.', 325);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-326', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'French casualties at Verdun were approximately:', '100,000', '250,000', '542,000', '800,000', 2, 'The Battle of Verdun (February-December 1916) cost approximately 542,000 French casualties and 430,000 German dead. After 10 months, France held Verdun and Germany gained only 8 km.', 326);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-327', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'The Brusilov Offensive (1916) gained how much territory in its first month?', '8 km', '25 km', '65 km', '96 km', 3, 'The Brusilov Offensive gained 96 km in its first month (June 1916) against Austria-Hungary. It stalled by July due to insufficient supplies, but it totally crippled the Austro-Hungarian military.', 327);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-328', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'The Zimmerman Telegram encouraged which country to invade the United States?', 'Canada', 'Cuba', 'Mexico', 'Japan', 2, 'The Zimmerman Telegram (1917) encouraged Mexico to invade the US. This backfired catastrophically for Germany — instead of keeping the US focused on a war with Mexico, it helped bring the US into WWI.', 328);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-329', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'Under the Treaty of Brest-Litovsk, Russia lost what percentage of its coal?', '25%', '50%', '75%', '90%', 3, 'Russia lost 90% of its coal, 75% of its iron ore, 50% of its industry, 55 million people, half its agricultural land, and 2.6 million km2 of territory under the Treaty of Brest-Litovsk.', 329);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-330', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'The Ludendorff Offensive used which new tactic?', 'Trench mining', 'Infiltration tactics with stormtroopers', 'Naval bombardment of trenches', 'Aerial carpet bombing', 1, 'The Ludendorff Offensive used infiltration tactics — smaller stormtrooper detachments attacking weak points for surprise and speed. Combined with hurricane barrages, they initially gained 65 km in the first week before stalling.', 330);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-331', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'At the Battle of Jutland (1916), who lost more ships?', 'Germany (14 ships lost)', 'Britain (14 ships lost)', 'They lost an equal number', 'Neither side lost any ships', 1, 'Britain lost 14 ships at Jutland compared to Germany''s 11. However, the battle was strategically inconclusive — the British maintained their blockade and the German navy remained largely confined to port.', 331);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-332', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'Fritz Fischer''s interpretation of WWI was that:', 'All powers shared equal responsibility', 'Germany deliberately planned and sought the war', 'Britain was primarily responsible', 'The war was an accident caused by miscommunication', 1, 'Fritz Fischer argued Germany deliberately sought war for annexation and colonial expansion. Gerhard Ritter disagreed, noting annexation plans were made when war was underway. The consensus settled on collective responsibility with emphasis on German actions.', 332);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-333', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'Spanish Influenza (1918-1920) killed approximately:', '10 million people', '50 million people', '120 million people', '200 million people', 2, 'Spanish Influenza killed approximately 120 million people (6% of the world population). In the war, 500,000 German troops were too ill to fight, significantly impacting the final phase of the conflict.', 333);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-334', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'Poison gas in WWI accounted for what proportion of total fatalities?', 'Less than 1%', 'About 5%', 'About 15%', 'About 25%', 0, 'Poison gas caused less than 1% of total war fatalities. Its significance was primarily psychological rather than strategic. Both sides deployed gas but effective countermeasures (gas masks) limited its tactical impact.', 334);

-- ── B4. New Written Questions ────────────────────────────────────────────

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-140', '2. World War I (1914-1918)', 'SL/HL', 'short_answer', 'P2-WAR', 15, 'To what extent was Germany responsible for the outbreak of World War I?', '• Band 5 (13-15): Evaluative argument engaging with the historiographical debate. Fischer: Germany deliberately sought war for expansion. Fay: collective responsibility. Winter: "Germany brought about WWI as part of a political community." Evidence for German responsibility: blank cheque, Weltpolitik, naval arms race, refusal of British conference proposal, Schlieffen Plan requiring rapid action. Evidence against sole responsibility: alliance system dynamics, Russian mobilisation, Austro-Hungarian aggression, Balkan nationalism, imperial rivalries. Must reach a substantiated judgement.
• Band 3 (7-9): Some engagement with historiography but limited evidence or imbalanced argument.
• Band 1 (1-3): Simple assertion about blame without supporting evidence.', 140);

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-141', '2. World War I (1914-1918)', 'SL/HL', 'short_answer', 'P2-WAR', 15, 'To what extent did the long-term causes of WWI make conflict inevitable by 1914?', '• Band 5 (13-15): Evaluative analysis of ANIMAL framework causes. Alliances: created encirclement fears, but terms were vague and did not compel action. Nationalism: glorified military strength, assimilated Social Darwinism, created atmosphere where war was an "opportunity." Imperialism: new arena for conflict (Moroccan Crises), but most imperial disputes resolved diplomatically. Militarism: arms race, Dreadnoughts, standing armies growing, war plans (Schlieffen) requiring rapid action. Must argue whether these made war inevitable or whether a crisis was still necessary. Short-term causes and miscalculations also needed to trigger actual war.
• Band 3 (7-9): Some discussion of causes but limited evaluation of inevitability.
• Band 1 (1-3): Simple listing of causes without analysis.', 141);

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-142', '2. World War I (1914-1918)', 'SL/HL', 'short_answer', 'P2-WAR', 15, 'Evaluate the significance of technology in determining the outcome of World War I.', '• Band 5 (13-15): Detailed analysis of specific technologies with evaluation of their impact. Machine guns: created stalemate (500 rpm), Britain massively outproduced Germany (120,900 vs 13,000 by 1918). Tanks: from 1916, initially basic but by 1918 5,000+ used effectively. Poison gas: less than 1% of fatalities, mainly psychological. Aircraft: reconnaissance then combat, supported ground troops. Submarines: U-boats sank 748,000 tons (1915), nearly starved Britain. Railways: critical for mobilisation and logistics. Must evaluate whether technology determined the outcome or whether other factors (US entry, blockade, leadership, morale) were more significant.
• Band 3 (7-9): Some relevant examples but limited evaluation of relative significance.
• Band 1 (1-3): Vague listing of technologies without analysis.', 142);

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-143', '2. World War I (1914-1918)', 'SL/HL', 'short_answer', 'P2-WAR', 15, 'How significant was the management of the war in determining its outcome?', '• Band 5 (13-15): Analysis of military leadership and strategic decisions. Failed strategies: Schlieffen Plan (logistics failure, railheads 135km behind), Verdun (10 months for 8km), Somme (54,740 casualties day 1). Successful adaptations: Allied combined arms (tanks + aircraft), convoy system against U-boats, Brusilov Offensive tactics. Ludendorff Offensive used innovative infiltration tactics but failed due to overextension. All plans assumed short war — if leaders knew the war''s length, they may have been more hesitant. Must evaluate management against other factors: resources, US entry, home front, disease (Spanish flu).
• Band 3 (7-9): Some discussion of military decisions but limited evaluation of significance.
• Band 1 (1-3): Vague assertions about leadership without specific examples.', 143);

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-144', '2. World War I (1914-1918)', 'SL/HL', 'short_answer', 'P2-WAR', 15, 'Did the impact of WWI make future European conflict more or less likely?', '• Band 5 (13-15): Evaluative argument considering multiple consequences. More likely: Treaty of Versailles resentment (war guilt, reparations, territorial losses), creation of many new democratic states prone to instability, economic disruption, rise of extremist ideologies (communism, fascism), failure of League of Nations, unresolved ethnic tensions. Less likely: horror of war should have deterred conflict, League of Nations created mechanisms for peaceful resolution, democratic spread, disarmament efforts. Must reach a clear judgement with specific evidence linking WWI outcomes to subsequent developments (Weimar instability, rise of Hitler, WWII).
• Band 3 (7-9): Some analysis of consequences but limited evaluation of likelihood of future conflict.
• Band 1 (1-3): Simple assertion without evidence.', 144);
