-- ════════════════════════════════════════════════════════════════════════════
-- 0046 · Fix UKHC MCQs & Written Qs — re-insert with non-conflicting IDs
--        Migration 0045 used IDs that already existed in 0042 (Cold War,
--        Democracy, Independence content). INSERT OR IGNORE silently dropped
--        all 35 MCQs and 12 written questions. This migration re-adds them
--        with new IDs: MCQs 400-434, Written Qs 200-211.
-- ════════════════════════════════════════════════════════════════════════════


-- ══════════════════════════════════════════════════════════════════════════
-- A. CASTRO'S CUBA MCQs (was 300-319, now 400-419)
-- ══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-400', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'The Moncada Barracks attack took place in:', '1950', '1953', '1956', '1959', 1, 'The Moncada Barracks attack occurred on 26 July 1953. Though it failed militarily, it gave Castro national prominence through his trial and "History Will Absolve Me" speech.', 400);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-401', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'Castro''s guerrilla forces in the Sierra Maestra never exceeded approximately:', '200 men', '2,000 men', '10,000 men', '50,000 men', 1, 'The rebel army never exceeded approximately 2,000 men (estimates range from 300 to 8,000 but 2,000 is the best estimate, according to Wolf). Despite this small size, they defeated Batista''s much larger conventional forces.', 401);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-402', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'Which battle saw Che Guevara defeat forces at a 300:4000 ratio?', 'Battle of La Plata', 'Battle of Santa Clara', 'Battle of El Uvero', 'Battle of Havana', 1, 'On 31 December 1958, Che Guevara captured Santa Clara with a roughly 300:4000 troop ratio, demonstrating the competence of the Fidelistas. Batista fled Cuba the same day.', 402);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-403', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'The Bay of Pigs invasion occurred in:', 'January 1959', 'April 1961', 'October 1962', 'March 1960', 1, 'The CIA-backed Bay of Pigs invasion took place in April 1961 and failed miserably. Castro used it to highlight US interference and consolidate domestic support.', 403);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-404', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'What percentage of Cuba''s trade was with the Soviet Union before 1991?', '50%', '65%', '85%', '95%', 2, 'The Soviet bloc accounted for 85% of Cuba''s trading partners. The collapse of the USSR in 1991 led to a 40% decline in Cuba''s economy, triggering the Special Period.', 404);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-405', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'The Torricelli Act restricting trade with Cuba was passed in:', '1989', '1992', '1996', '2000', 1, 'The Torricelli Act was passed in 1992, followed by the Helms-Burton Act in 1996. Both aimed to tighten the US trade embargo against Cuba during the Special Period.', 405);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-406', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'Cuba''s 1961 literacy campaign raised literacy rates to approximately:', '70%', '85%', '96%', '100%', 2, 'The 1961 literacy campaign raised literacy from 40% to a reported 96%, the highest in Latin America and one of the highest in the world at the time.', 406);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-407', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'The number of teachers in Cuba increased from 20,000 pre-Revolution to how many by 1963?', '30,000', '45,000', '60,000', '100,000', 2, 'The number of teachers tripled from 20,000 to 60,000 between the pre-Revolution period and 1963, though this was partially offset by the brain drain of teachers leaving Cuba (1959-1961).', 407);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-408', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'The Federation of Cuban Women was established in:', '1953', '1959', '1960', '1965', 2, 'The Federation of Cuban Women (FMC) was established in 1960 to integrate women into the workforce and promote female literacy and gender equality. It expanded to 2.6 million members.', 408);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-409', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'Women''s employment in Cuba rose from 13% in 1958 to what percentage by 2008?', '25%', '33%', '44%', '55%', 2, 'Women''s employment rose from 13% (1958) to 44% (2008). Women also held 43% of parliamentary seats by 2008, though cultural resistance (machismo) limited the real impact of gender policies.', 409);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-410', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'The 1975 Family Code in Cuba aimed to:', 'Restrict women''s access to education', 'Dismantle patriarchal family structures and mandate shared domestic labour', 'Encourage higher birth rates', 'Nationalise childcare entirely', 1, 'The 1975 Family Code aimed to create egalitarian family law, requiring men to do half the chores, providing maternity cover, abortions, and day-care, and simplifying divorce. However, it was largely ignored in practice.', 410);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-411', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'Which of the following was NOT a guerrilla tactic used by Castro in the Sierra Maestra?', 'Hit-and-run attacks', 'Small autonomous groups', 'Large-scale frontal assaults on cities', 'Retreating when attacked', 2, 'Castro''s guerrillas used classic guerrilla tactics: retreat when attacked, hit-and-run attacks, small autonomous groups, and mobile forces with peasant support. They avoided large-scale frontal assaults, which was Batista''s failing strategy.', 411);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-412', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'Radio Rebelde was significant because it:', 'Was used by Batista to spread propaganda', 'Became the most popular radio station in Cuba, spreading Castro''s message', 'Was funded by the CIA', 'Broadcast exclusively in English for international audiences', 1, 'Radio Rebelde became the most popular radio station in Cuba, spreading revolutionary propaganda and Castro''s message from the Sierra Maestra. Along with the newspaper El Cubano Libre, it was key to building support.', 412);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-413', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'The Escambray Rebellion was primarily composed of:', 'Communist guerrillas', 'Wealthier peasants, middle class, and Batista loyalists opposing Castro', 'Foreign mercenaries', 'University students', 1, 'The Escambray rebels were mainly wealthier peasants, middle class, and local farmers who opposed expropriation and reorganisation, plus Batista loyalists. They had no outstanding leaders, were outnumbered, and lacked popular support.', 413);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-414', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'Castro''s period of consolidation is generally considered to be:', '1953-1956', '1956-1959', '1959-1965', '1965-1975', 2, 'The consolidation period was 1959-1965 — from Castro taking power to when all active external and internal opposition had been eliminated. His key acts were 1959-1961, and foreign opposition died down by 1965.', 414);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-415', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'Which historian described Cuba''s education policies as achieving egalitarian goals more than anywhere else?', 'Fischer', 'Perez', 'Tanay', 'Wolf', 1, 'Perez stated: "Nowhere was the quest for an egalitarian society more fully attained than in the area of education." This reflects the widely acknowledged success of Castro''s education reforms.', 415);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-416', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'What was a key pragmatic economic response during Cuba''s Special Period?', 'Increased trade with the USSR', 'Dollarisation of the economy and inviting foreign firms', 'Nationalisation of all remaining private businesses', 'Military expansion', 1, 'During the Special Period, Cuba pursued pragmatic policies including dollarisation, encouraging private enterprise, and inviting foreign firms (1995). However, under George W. Bush''s pressure, Cuba moved against dollarisation by 2004.', 416);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-417', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'Cuba''s population grew from 5.8 million in 1953 to approximately how many by 1970?', '6.5 million', '7.5 million', '8.5 million', '10 million', 2, 'Cuba''s population increased from 5.8 million (1953) to 8.5 million (1970). Birth rates surged from 27/1000 (1958) to 37/1000 (1962), though this increase did not sustain long-term.', 417);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-418', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'What was the Pact of Caracas (1958)?', 'A military alliance between Cuba and Venezuela', 'An agreement by all opposition groups to end Batista''s regime and restore democracy', 'A trade deal between Cuba and the Soviet Union', 'A peace treaty ending the Cuban Revolution', 1, 'The Pact of Caracas (1958) saw all opposition groups agree to end the Batista regime and restore democracy. Castro, however, did not follow through on the democratic restoration promise after taking power.', 418);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-419', '6. Cuba (Castro)', 'SL/HL', 'P2-AUTH', 'By the mid-1990s, how many dissident groups had emerged in Cuba?', 'Fewer than 10', 'Over 50', 'Over 200', 'Over 500', 1, 'By the mid-1990s, over 50 dissident groups had emerged — the first time since 1965 with such significant dissidence. However, Castro''s regime quelled this opposition with force, arresting 100 members of Concilio Cubano in 1996.', 419);


-- ══════════════════════════════════════════════════════════════════════════
-- B. CASTRO'S CUBA WRITTEN QUESTIONS (was 130-136, now 200-206)
-- ══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-200', '6. Cuba (Castro)', 'SL/HL', 'short_answer', 'P2-AUTH', 15, 'Evaluate the role of guerrilla warfare in Castro''s rise to power.', '• Band 5 (13-15): Detailed analysis of guerrilla tactics (retreat when attacked, hit-and-run, small autonomous groups, peasant support) and their effectiveness against Batista''s conventional forces. Must discuss specific engagements (La Plata, El Uvero, Santa Clara) with evidence. Should also evaluate the role of propaganda (Radio Rebelde, NYT interview) and political factors alongside military ones. The rebel army never exceeded ~2,000 men yet defeated a much larger force.
• Band 3 (7-9): Some relevant knowledge of guerrilla tactics but limited specific evidence or evaluation of relative importance.
• Band 1 (1-3): Vague description with no specific military engagements or analysis.', 200);

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-201', '6. Cuba (Castro)', 'SL/HL', 'short_answer', 'P2-AUTH', 15, 'To what extent was Castro''s consolidation of power (1959-65) reliant on the use of force?', '• Band 5 (13-15): Balanced evaluation weighing use of force (trials/executions, crushing Escambray Rebellion, suppressing Matos/Morgan) against other methods: legal methods (nationalisation, land reform), charismatic leadership (personal appeal, eating same rations as troops), propaganda (Radio Rebelde, highlighting Bay of Pigs as US interference), and ideological flexibility. Must consider that consolidation was complete by 1965.
• Band 3 (7-9): Some analysis of force and other methods but may lack balance or specific evidence.
• Band 1 (1-3): Simple assertion about force with no supporting evidence.', 201);

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-202', '6. Cuba (Castro)', 'SL/HL', 'short_answer', 'P2-AUTH', 15, 'Evaluate the successes and limitations of Castro''s social policies in education and healthcare.', '• Band 5 (13-15): Detailed evaluation with specific statistics. Education: teachers 20,000→60,000, literacy 40%→96%, primary enrollment 800,000→3.3M, secondary schools 80→1,900. Perez: "nowhere was the quest for an egalitarian society more fully attained than in education." Healthcare: free for all, 1,100 doctors/year, polio eliminated, malaria-free. BUT: brain drain of teachers 1959-61, indoctrination concerns, medicine shortages due to embargo, healthcare gains did not survive Special Period. Must reach a balanced judgement.
• Band 3 (7-9): Some statistics but limited evaluation of successes vs. limitations.
• Band 1 (1-3): General claims about education/healthcare without evidence.', 202);

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-203', '6. Cuba (Castro)', 'SL/HL', 'short_answer', 'P2-AUTH', 15, 'To what extent did the Special Period (1991-96) threaten Castro''s hold on power?', '• Band 5 (13-15): Detailed analysis of the crisis: USSR collapse, 85% of trade lost, economy fell 40%, severe hardship (no fuel, power shortages), Torricelli Act (1992), Helms-Burton Act (1996). Response: pragmatic policies (dollarisation, private enterprise, foreign firms), ideological emphasis, US as bogeyman uniting Cubans. 50+ dissident groups emerged but were suppressed (Concilio Cubano arrests 1996). Must evaluate whether the regime was genuinely threatened or adapted effectively.
• Band 3 (7-9): Some knowledge of the Special Period but limited analysis of the threat to power.
• Band 1 (1-3): Vague awareness of economic difficulties without specific evidence.', 203);

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-204', '6. Cuba (Castro)', 'SL/HL', 'short_answer', 'P2-AUTH', 15, 'Evaluate the impact of Castro''s policies on women in Cuba.', '• Band 5 (13-15): Detailed analysis of policies and their real impact. Achievements: Federation of Cuban Women (1960, 2.6M members), employment 13%→44%, 43% of parliament (2008), literacy campaign mobilised 100,000 women (56% of newly literate were women), women dominate higher education (70% med school 2008). 1975 Family Code mandated equality. 1968 nationalisation: 90% of new administrators were women. BUT: Family Code largely ignored (women did 75% of domestic labour in 1990s), 76% of women who entered labour force in 1969 dropped out within a year, cultural machismo persisted, Special Period pushed women into sex work. Tanay: "good intentions, but fundamentally useless."
• Band 3 (7-9): Some knowledge of policies but limited analysis of gap between policy and reality.
• Band 1 (1-3): Vague claims about gender equality without evidence.', 204);

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-205', '6. Cuba (Castro)', 'SL/HL', 'short_answer', 'P2-AUTH', 15, 'Compare and contrast the emergence of Castro and one other authoritarian leader.', '• Band 5 (13-15): Systematic comparison of conditions (economic, political, social) and methods (use of force, propaganda, legal, charismatic) for Castro and another leader (e.g., Hitler, Mao). Castro: Batista''s corruption, US economic dominance, guerrilla warfare, Moncada/Sierra Maestra, propaganda (Radio Rebelde). Must show genuine comparison with similarities and differences, not two separate narratives.
• Band 3 (7-9): Some comparison but may be largely descriptive or two separate accounts.
• Band 1 (1-3): Vague comparison with no specific evidence from either case.', 205);

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-206', '6. Cuba (Castro)', 'SL/HL', 'short_answer', 'P2-AUTH', 15, 'To what extent did Castro achieve authoritarian control over Cuba?', '• Band 5 (13-15): Evaluative argument assessing the degree of control. Evidence of control: one-party state, elimination of opposition by 1965, censorship, CDR surveillance, control of education as propaganda. Evidence of limitations: Special Period dissidence (50+ groups), brain drain/emigration, economic failures, cultural resistance to social policies (machismo, Family Code ignored), reliance on USSR. Must define what "authoritarian control" means and reach a clear judgement.
• Band 3 (7-9): Some analysis but may overstate or understate degree of control.
• Band 1 (1-3): Simple assertion without evidence or criteria for judgement.', 206);


-- ══════════════════════════════════════════════════════════════════════════
-- C. WWI DETAIL MCQs (was 320-334, now 420-434)
-- ══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-420', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'The Concert of Europe originated from:', 'The Treaty of Versailles (1919)', 'The Congress of Vienna (1814-15)', 'The Berlin Conference (1884-85)', 'The Hague Conventions (1899)', 1, 'The Concert of Europe was an informal system of maintaining European balance of power that emerged from the Congress of Vienna (1814-15), held after Napoleon''s defeat.', 420);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-421', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'Austria-Hungary annexed Bosnia-Herzegovina in:', '1878', '1903', '1908', '1914', 2, 'Austria-Hungary annexed Bosnia-Herzegovina in 1908. Russia was unable to respond militarily but was furious, and determined to prevent further Austrian expansion in the Balkans.', 421);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-422', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'Weltpolitik was the foreign policy of:', 'Tsar Nicholas II', 'Kaiser Wilhelm II', 'King Edward VII', 'Emperor Franz Joseph', 1, 'Weltpolitik was Kaiser Wilhelm II''s policy of extending German influence worldwide through a powerful navy and colonial expansion. He declared "nothing must henceforth be settled in the world without the intervention of Germany."', 422);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-423', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'By 1914, how many Dreadnought-class battleships did Britain have compared to Germany?', 'Britain 17, Germany 29', 'Britain 29, Germany 17', 'Britain 20, Germany 20', 'Britain 10, Germany 25', 1, 'By 1914 Britain had 29 Dreadnoughts to Germany''s 17. In 1906, Britain had 1 and Germany had none. The naval arms race was a key source of Anglo-German tension.', 423);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-424', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'Germany''s "blank cheque" to Austria-Hungary was issued on:', '28 June 1914', '6 July 1914', '26 July 1914', '1 August 1914', 1, 'On 6 July 1914, Germany offered Austria-Hungary unconditional support (the "blank cheque") against Serbia. This emboldened Austria-Hungary to issue its deliberately harsh ultimatum.', 424);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-425', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'The Germans were stopped at which battle in September 1914, ending the Schlieffen Plan?', 'Battle of Tannenberg', 'Battle of the Marne', 'Battle of Verdun', 'Battle of Ypres', 1, 'The Germans were stopped at the Battle of the Marne (6-9 September 1914). Both sides then entrenched, leading to the "Race to the Sea" and the trench warfare stalemate.', 425);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-426', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'French casualties at Verdun were approximately:', '100,000', '250,000', '542,000', '800,000', 2, 'The Battle of Verdun (February-December 1916) cost approximately 542,000 French casualties and 430,000 German dead. After 10 months, France held Verdun and Germany gained only 8 km.', 426);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-427', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'The Brusilov Offensive (1916) gained how much territory in its first month?', '8 km', '25 km', '65 km', '96 km', 3, 'The Brusilov Offensive gained 96 km in its first month (June 1916) against Austria-Hungary. It stalled by July due to insufficient supplies, but it totally crippled the Austro-Hungarian military.', 427);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-428', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'The Zimmerman Telegram encouraged which country to invade the United States?', 'Canada', 'Cuba', 'Mexico', 'Japan', 2, 'The Zimmerman Telegram (1917) encouraged Mexico to invade the US. This backfired catastrophically for Germany — instead of keeping the US focused on a war with Mexico, it helped bring the US into WWI.', 428);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-429', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'Under the Treaty of Brest-Litovsk, Russia lost what percentage of its coal?', '25%', '50%', '75%', '90%', 3, 'Russia lost 90% of its coal, 75% of its iron ore, 50% of its industry, 55 million people, half its agricultural land, and 2.6 million km2 of territory under the Treaty of Brest-Litovsk.', 429);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-430', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'The Ludendorff Offensive used which new tactic?', 'Trench mining', 'Infiltration tactics with stormtroopers', 'Naval bombardment of trenches', 'Aerial carpet bombing', 1, 'The Ludendorff Offensive used infiltration tactics — smaller stormtrooper detachments attacking weak points for surprise and speed. Combined with hurricane barrages, they initially gained 65 km in the first week before stalling.', 430);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-431', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'At the Battle of Jutland (1916), who lost more ships?', 'Germany (14 ships lost)', 'Britain (14 ships lost)', 'They lost an equal number', 'Neither side lost any ships', 1, 'Britain lost 14 ships at Jutland compared to Germany''s 11. However, the battle was strategically inconclusive — the British maintained their blockade and the German navy remained largely confined to port.', 431);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-432', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'Fritz Fischer''s interpretation of WWI was that:', 'All powers shared equal responsibility', 'Germany deliberately planned and sought the war', 'Britain was primarily responsible', 'The war was an accident caused by miscommunication', 1, 'Fritz Fischer argued Germany deliberately sought war for annexation and colonial expansion. Gerhard Ritter disagreed, noting annexation plans were made when war was underway. The consensus settled on collective responsibility with emphasis on German actions.', 432);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-433', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'Spanish Influenza (1918-1920) killed approximately:', '10 million people', '50 million people', '120 million people', '200 million people', 2, 'Spanish Influenza killed approximately 120 million people (6% of the world population). In the war, 500,000 German troops were too ill to fight, significantly impacting the final phase of the conflict.', 433);

INSERT OR IGNORE INTO history_mcq_questions (id, category, difficulty, unit, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, sort_order) VALUES ('hist-p2-mcq-434', '2. World War I (1914-1918)', 'SL/HL', 'P2-WAR', 'Poison gas in WWI accounted for what proportion of total fatalities?', 'Less than 1%', 'About 5%', 'About 15%', 'About 25%', 0, 'Poison gas caused less than 1% of total war fatalities. Its significance was primarily psychological rather than strategic. Both sides deployed gas but effective countermeasures (gas masks) limited its tactical impact.', 434);


-- ══════════════════════════════════════════════════════════════════════════
-- D. WWI DETAIL WRITTEN QUESTIONS (was 140-144, now 207-211)
-- ══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-207', '2. World War I (1914-1918)', 'SL/HL', 'short_answer', 'P2-WAR', 15, 'To what extent was Germany responsible for the outbreak of World War I?', '• Band 5 (13-15): Evaluative argument engaging with the historiographical debate. Fischer: Germany deliberately sought war for expansion. Fay: collective responsibility. Winter: "Germany brought about WWI as part of a political community." Evidence for German responsibility: blank cheque, Weltpolitik, naval arms race, refusal of British conference proposal, Schlieffen Plan requiring rapid action. Evidence against sole responsibility: alliance system dynamics, Russian mobilisation, Austro-Hungarian aggression, Balkan nationalism, imperial rivalries. Must reach a substantiated judgement.
• Band 3 (7-9): Some engagement with historiography but limited evidence or imbalanced argument.
• Band 1 (1-3): Simple assertion about blame without supporting evidence.', 207);

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-208', '2. World War I (1914-1918)', 'SL/HL', 'short_answer', 'P2-WAR', 15, 'To what extent did the long-term causes of WWI make conflict inevitable by 1914?', '• Band 5 (13-15): Evaluative analysis of ANIMAL framework causes. Alliances: created encirclement fears, but terms were vague and did not compel action. Nationalism: glorified military strength, assimilated Social Darwinism, created atmosphere where war was an "opportunity." Imperialism: new arena for conflict (Moroccan Crises), but most imperial disputes resolved diplomatically. Militarism: arms race, Dreadnoughts, standing armies growing, war plans (Schlieffen) requiring rapid action. Must argue whether these made war inevitable or whether a crisis was still necessary. Short-term causes and miscalculations also needed to trigger actual war.
• Band 3 (7-9): Some discussion of causes but limited evaluation of inevitability.
• Band 1 (1-3): Simple listing of causes without analysis.', 208);

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-209', '2. World War I (1914-1918)', 'SL/HL', 'short_answer', 'P2-WAR', 15, 'Evaluate the significance of technology in determining the outcome of World War I.', '• Band 5 (13-15): Detailed analysis of specific technologies with evaluation of their impact. Machine guns: created stalemate (500 rpm), Britain massively outproduced Germany (120,900 vs 13,000 by 1918). Tanks: from 1916, initially basic but by 1918 5,000+ used effectively. Poison gas: less than 1% of fatalities, mainly psychological. Aircraft: reconnaissance then combat, supported ground troops. Submarines: U-boats sank 748,000 tons (1915), nearly starved Britain. Railways: critical for mobilisation and logistics. Must evaluate whether technology determined the outcome or whether other factors (US entry, blockade, leadership, morale) were more significant.
• Band 3 (7-9): Some relevant examples but limited evaluation of relative significance.
• Band 1 (1-3): Vague listing of technologies without analysis.', 209);

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-210', '2. World War I (1914-1918)', 'SL/HL', 'short_answer', 'P2-WAR', 15, 'How significant was the management of the war in determining its outcome?', '• Band 5 (13-15): Analysis of military leadership and strategic decisions. Failed strategies: Schlieffen Plan (logistics failure, railheads 135km behind), Verdun (10 months for 8km), Somme (54,740 casualties day 1). Successful adaptations: Allied combined arms (tanks + aircraft), convoy system against U-boats, Brusilov Offensive tactics. Ludendorff Offensive used innovative infiltration tactics but failed due to overextension. All plans assumed short war — if leaders knew the war''s length, they may have been more hesitant. Must evaluate management against other factors: resources, US entry, home front, disease (Spanish flu).
• Band 3 (7-9): Some discussion of military decisions but limited evaluation of significance.
• Band 1 (1-3): Vague assertions about leadership without specific examples.', 210);

INSERT OR IGNORE INTO history_written_questions (id, category, difficulty, question_type, unit, marks, question_text, mark_scheme, sort_order) VALUES ('hist-p2-wq-211', '2. World War I (1914-1918)', 'SL/HL', 'short_answer', 'P2-WAR', 15, 'Did the impact of WWI make future European conflict more or less likely?', '• Band 5 (13-15): Evaluative argument considering multiple consequences. More likely: Treaty of Versailles resentment (war guilt, reparations, territorial losses), creation of many new democratic states prone to instability, economic disruption, rise of extremist ideologies (communism, fascism), failure of League of Nations, unresolved ethnic tensions. Less likely: horror of war should have deterred conflict, League of Nations created mechanisms for peaceful resolution, democratic spread, disarmament efforts. Must reach a clear judgement with specific evidence linking WWI outcomes to subsequent developments (Weimar instability, rise of Hitler, WWII).
• Band 3 (7-9): Some analysis of consequences but limited evaluation of likelihood of future conflict.
• Band 1 (1-3): Simple assertion without evidence.', 211);
