name = "ib-grading-hollen"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "USER_DATA"
id = "9a2b38ab7ed94ec996ef5e4d08a47919"

[[d1_databases]]
binding = "DB"
database_name = "ib-revision-db"
database_id = "9fe17329-2e73-496c-9cee-1bb3a8f36d9e"
